
# Permalinks
permalink:        pretty

# Setup
title:            Acupunctuur Ammerlaan
tagline:          'A Jekyll theme'
description:      'PRAKTIJK VOOR ACUPUNCTUUR<br>T.C.M Ammerlaan, Lid N.V.A'
url:              http://hyde.getpoole.com
baseurl:          /hyde/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
